### What is numpy?

##### NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


##### At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

##### - NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

##### - The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

##### - NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

##### - A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [1]:
# np.array

import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [5]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
# with reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [11]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
#np.ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.zeros

np.zeros((3,4))

In [16]:
# Random

np.random.random((3,4))

array([[0.31472845, 0.43771332, 0.61185854, 0.00370465],
       [0.09799361, 0.65644729, 0.03979565, 0.28567014],
       [0.10221992, 0.78210593, 0.05779337, 0.78587218]])

In [18]:
# np.linspace
np.linspace(-10,5,10,dtype=int)

array([-10,  -9,  -7,  -5,  -4,  -2,   0,   1,   3,   5])

In [19]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [21]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [24]:
# ndim it shows the no. of dimensions

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [25]:
# shape
print(a3.shape)
print(a2.shape)
print(a1.shape)

(2, 2, 2)
(3, 4)
(10,)


In [27]:
# size
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [30]:
# dtype   
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int32
float64
int64


In [31]:
# itemsize  it shows how many bit it takes 
print(a3.itemsize)
print(a2.itemsize)
print(a1.itemsize)

8
8
4


In [32]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [40]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print("***********"*2)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**********************
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [41]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [42]:
a2 * 2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [44]:
# relational
a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [4]:
import numpy as np

In [5]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[49., 99., 84.],
       [28., 37., 89.],
       [14., 62., 25.]])

In [6]:
# max/min/sum/prod
# 0 -> col and 1 -> row

In [12]:
np.prod(a1)

np.float64(815304907771200.0)

In [14]:
np.max(a1)

np.float64(99.0)

In [15]:
np.min(a1)

np.float64(14.0)

In [16]:
np.sum(a1)

np.float64(487.0)

In [17]:
np.prod(a1,axis=0)

array([ 19208., 227106., 186900.])

In [18]:
# mean/median/std/var

In [19]:
np.var(a1,axis=1)

array([438.88888889, 722.88888889, 421.55555556])

In [20]:
np.mean(a1,axis=1)

array([77.33333333, 51.33333333, 33.66666667])

In [21]:
np.median(a1,axis=1)

array([84., 37., 25.])

In [22]:
np.std(a1,axis=1)

array([20.94967515, 26.88659311, 20.53181813])

In [23]:
# trigonomoetric functions
np.sin(a1)

array([[-0.95375265, -0.99920683,  0.73319032],
       [ 0.27090579, -0.64353813,  0.86006941],
       [ 0.99060736, -0.7391807 , -0.13235175]])

In [24]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [25]:
# log and exponents
np.exp(a1)

array([[1.90734657e+21, 9.88903032e+42, 3.02507732e+36],
       [1.44625706e+12, 1.17191424e+16, 4.48961282e+38],
       [1.20260428e+06, 8.43835667e+26, 7.20048993e+10]])

In [26]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[42., 97., 42.],
       [ 9., 80., 21.]])

## Indexing & Slicing

In [27]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [28]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a2[1,2]

np.int64(6)

In [32]:
a3[1,0,1]

np.int64(5)

In [40]:
a3[0,0,0]

np.int64(0)

In [34]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1[2:5:2]

array([2, 4])

In [41]:
# Slicing

In [42]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a1[2:5]

array([2, 3, 4])

In [44]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a2[0,:]

array([0, 1, 2, 3])

In [50]:
a2[:,2]

array([ 2,  6, 10])

In [51]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [53]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [57]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [58]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [59]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [60]:
a3[0,1,:]

array([3, 4, 5])

In [61]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

###  Iterating

In [15]:
import numpy as np

In [4]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [6]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [8]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [12]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [14]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [16]:
# Reshape

In [17]:
# Transpose

np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [19]:
# Ravel  To covert 3d array in 1d array

a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [23]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [22]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [25]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [27]:
# vertical splitting

In [28]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]