### Numpy Hidden Functions

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# Code

import numpy as np

a = np.random.randint(1,100,15)
a

array([14, 28, 84, 19, 19, 57, 17, 46, 75, 18, 92, 11, 56, 86, 78],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[ 9, 70,  1, 92],
       [18, 69, 50, 78],
       [38, 30,  1,  3],
       [19, 93, 59, 22],
       [31, 41, 29, 34],
       [54, 68, 87, 67]], dtype=int32)

In [5]:
np.sort(a)

array([11, 14, 17, 18, 19, 19, 28, 46, 56, 57, 75, 78, 84, 86, 92],
      dtype=int32)

In [6]:
np.sort(a)[::-1]

array([92, 86, 84, 78, 75, 57, 56, 46, 28, 19, 19, 18, 17, 14, 11],
      dtype=int32)

In [8]:
np.sort(b,axis = 0)

array([[ 9, 30,  1,  3],
       [18, 41,  1, 22],
       [19, 68, 29, 34],
       [31, 69, 50, 67],
       [38, 70, 59, 78],
       [54, 93, 87, 92]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
a

array([14, 28, 84, 19, 19, 57, 17, 46, 75, 18, 92, 11, 56, 86, 78],
      dtype=int32)

In [12]:
# code
np.append(a,200)

array([ 14,  28,  84,  19,  19,  57,  17,  46,  75,  18,  92,  11,  56,
        86,  78, 200])

In [10]:
b

array([[ 9, 70,  1, 92],
       [18, 69, 50, 78],
       [38, 30,  1,  3],
       [19, 93, 59, 22],
       [31, 41, 29, 34],
       [54, 68, 87, 67]], dtype=int32)

In [13]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[ 9.        , 70.        ,  1.        , 92.        ,  0.55741408],
       [18.        , 69.        , 50.        , 78.        ,  0.73283181],
       [38.        , 30.        ,  1.        ,  3.        ,  0.48400743],
       [19.        , 93.        , 59.        , 22.        ,  0.14758365],
       [31.        , 41.        , 29.        , 34.        ,  0.55648356],
       [54.        , 68.        , 87.        , 67.        ,  0.38965417]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [17]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [19]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [22]:
# code

e = np.array([1,1,1,2,2,3,3,3,3,4,4,5,5,5,5,5,6,6,6,6,6,6,])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

##### With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [24]:
# code
a.shape

(15,)

In [25]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [26]:
np.expand_dims(a,axis=1)

array([[14],
       [28],
       [84],
       [19],
       [19],
       [57],
       [17],
       [46],
       [75],
       [18],
       [92],
       [11],
       [56],
       [86],
       [78]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [27]:
a

array([14, 28, 84, 19, 19, 57, 17, 46, 75, 18, 92, 11, 56, 86, 78],
      dtype=int32)

In [28]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  5,  8, 10, 12, 13, 14]),)

In [29]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([14, 28,  0, 19, 19,  0, 17, 46,  0, 18,  0, 11,  0,  0,  0],
      dtype=int32)

In [30]:
np.where(a%2 == 0,0,a)

array([ 0,  0,  0, 19, 19, 57, 17,  0, 75,  0,  0, 11,  0,  0,  0],
      dtype=int32)

### np.argmax

##### The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [32]:
# code
a

array([14, 28, 84, 19, 19, 57, 17, 46, 75, 18, 92, 11, 56, 86, 78],
      dtype=int32)

In [33]:
np.argmax(a)

np.int64(10)

In [34]:
np.argmax(b,axis=0)

array([5, 3, 5, 0])

In [35]:
np.argmax(b,axis=1)

array([3, 3, 0, 1, 1, 2])

In [36]:
# np.argmin
np.argmin(a)

np.int64(11)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [3]:
import numpy as np

In [8]:
a = np.random.randint(1,100,15)
b = np.random.randint(1,100,24).reshape(6,4)

In [9]:
a

array([62, 36,  5, 69, 69, 28,  2,  8, 15, 13, 31,  8, 22, 33, 70],
      dtype=int32)

In [10]:
b

array([[11, 24, 78, 86],
       [10, 88, 71, 29],
       [36,  9, 81, 46],
       [38, 32, 80, 83],
       [58, 41, 85, 69],
       [44, 18, 30, 44]], dtype=int32)

In [11]:
np.cumsum(a)

array([ 62,  98, 103, 172, 241, 269, 271, 279, 294, 307, 338, 346, 368,
       401, 471])

In [12]:
np.cumsum(b,axis=1)

array([[ 11,  35, 113, 199],
       [ 10,  98, 169, 198],
       [ 36,  45, 126, 172],
       [ 38,  70, 150, 233],
       [ 58,  99, 184, 253],
       [ 44,  62,  92, 136]])

In [13]:
# np.cumprod
np.cumprod(a)

array([                 62,                2232,               11160,
                    770040,            53132760,          1487717280,
                2975434560,         23803476480,        357052147200,
             4641677913600,     143892015321600,    1151136122572800,
         25324994696601600,  835724824987852800, 3160505528021041152])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [14]:
a

array([62, 36,  5, 69, 69, 28,  2,  8, 15, 13, 31,  8, 22, 33, 70],
      dtype=int32)

In [15]:
np.percentile(a,50)

np.float64(28.0)

In [16]:
np.median(a)

np.float64(28.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [17]:
a

array([62, 36,  5, 69, 69, 28,  2,  8, 15, 13, 31,  8, 22, 33, 70],
      dtype=int32)

In [18]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90])

(array([4, 2, 2, 3, 0, 0, 3, 1, 0]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [19]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [30]:
a = np.random.randint(1,100,15)

In [31]:
# code
a

array([77, 44,  4, 96, 72, 56, 12, 43, 46, 71, 40,  3, 37, 61, 20],
      dtype=int32)

In [33]:
items = [10,20,30,40,50,60,70,80,90,100]

[np.isin(a,items)]

[array([False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True])]

In [34]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([40, 20], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [35]:
# code
a

array([77, 44,  4, 96, 72, 56, 12, 43, 46, 71, 40,  3, 37, 61, 20],
      dtype=int32)

In [36]:
np.flip(a)

array([20, 61, 37,  3, 40, 71, 46, 43, 12, 56, 72, 96,  4, 44, 77],
      dtype=int32)

In [37]:
b

array([[11, 24, 78, 86],
       [10, 88, 71, 29],
       [36,  9, 81, 46],
       [38, 32, 80, 83],
       [58, 41, 85, 69],
       [44, 18, 30, 44]], dtype=int32)

In [38]:
np.flip(b,axis=1)

array([[86, 78, 24, 11],
       [29, 71, 88, 10],
       [46, 81,  9, 36],
       [83, 80, 32, 38],
       [69, 85, 41, 58],
       [44, 30, 18, 44]], dtype=int32)

In [39]:
np.flip(b,axis=0)

array([[44, 18, 30, 44],
       [58, 41, 85, 69],
       [38, 32, 80, 83],
       [36,  9, 81, 46],
       [10, 88, 71, 29],
       [11, 24, 78, 86]], dtype=int32)

In [41]:
np.flip(b)

array([[44, 30, 18, 44],
       [69, 85, 41, 58],
       [83, 80, 32, 38],
       [46, 81,  9, 36],
       [29, 71, 88, 10],
       [86, 78, 24, 11]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [48]:
# code
a

array([110, 530,   4,  96,  72,  53,  12,  43,  46,  71,  40,   3,  37,
        61,  20], dtype=int32)

In [47]:
np.put(a,[0,5],[110,53])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [49]:
# code
a

array([110, 530,   4,  96,  72,  53,  12,  43,  46,  71,  40,   3,  37,
        61,  20], dtype=int32)

In [52]:
np.delete(a,[1,5,7])

array([110,   4,  96,  72,  12,  46,  71,  40,   3,  37,  61,  20],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [55]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [56]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
np.intersect1d(m,n)

array([3, 4, 5])

In [58]:
np.setdiff1d(m,n)

array([1, 2])

In [59]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [60]:
m[np.in1d(m,1)]

C:\Users\majid\AppData\Local\Temp\ipykernel_25348\524887286.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [61]:
# code
a

array([110, 530,   4,  96,  72,  53,  12,  43,  46,  71,  40,   3,  37,
        61,  20], dtype=int32)

In [62]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 25, 75, 72, 53, 25, 43, 46, 71, 40, 25, 37, 61, 25],
      dtype=int32)